### ISSUE TITLE
Follow Google's C++ coding style

### ISSUE THREAD

**Issue by james075** [isndev/qb-linq#2]
@iSN-dev I think you should use google's C++ coding style from now long, it will make the code more maintainable. 

Check this out: https://google.github.io/styleguide/cppguide.html

nb: [refer](https://help.github.com/articles/autolinked-references-and-urls/) this issue on changes

**Comment by isndev** [comment]
@james075 I changed the coding style to be more readable, but it is not a real defect.
Thanks for your understanding.
